/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/test.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Plane.geometry} material={nodes.Plane.material} position={[0, -1.32, 0]} scale={10000} />
      <mesh geometry={nodes.Torus.geometry} material={materials['Material.002']} position={[0.21, 2.4, -1.48]} rotation={[2.42, 1.03, -0.02]} scale={1.26} />
    </group>
  )
}

useGLTF.preload('/test.gltf')
